name: Main

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened]
  
env:
    KOSLI_FLOW: sonarcloud_CLI_test
    KOSLI_TRAIL: ${{ github.sha }}
    KOSLI_HOST: https://staging.app.kosli.com
    KOSLI_ORG: FayeSGW
    KOSLI_API_TOKEN: ${{ secrets.KOSLI_API_TOKEN }}
    KOSLI_SONAR_API_TOKEN: ${{ secrets.SONAR_TOKEN }}
  
jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Setup Kosli CLI
        uses: kosli-dev/setup-cli-action@v2
        with:
          version: 2.10.15
  
      - name: Attest SonarCloud results to Kosli
        run:
          kosli attest sonar
            --dry-run
            --name=sonar-attest
            --sonar-project-key=FayeSGW_Freezer_Tracker
            --sonar-revision=$GITHUB_SHA
    
